export interface Country {
  code: string;
  displayName: string;
}

export const COUNTRIES = [
  { code: "AD", displayName: "Andorra" },
  { code: "AE", displayName: "United Arab Emirates" },
  { code: "AF", displayName: "Afghanistan" },
  { code: "AG", displayName: "Antigua & Barbuda" },
  { code: "AI", displayName: "Anguilla" },
  { code: "AL", displayName: "Albania" },
  { code: "AM", displayName: "Armenia" },
  { code: "AO", displayName: "Angola" },
  { code: "AQ", displayName: "Antarctica" },
  { code: "AR", displayName: "Argentina" },
  { code: "AS", displayName: "American Samoa" },
  { code: "AT", displayName: "Austria" },
  { code: "AU", displayName: "Australia" },
  { code: "AW", displayName: "Aruba" },
  { code: "AX", displayName: "Åland Islands" },
  { code: "AZ", displayName: "Azerbaijan" },
  { code: "BA", displayName: "Bosnia & Herzegovina" },
  { code: "BB", displayName: "Barbados" },
  { code: "BD", displayName: "Bangladesh" },
  { code: "BE", displayName: "Belgium" },
  { code: "BF", displayName: "Burkina Faso" },
  { code: "BG", displayName: "Bulgaria" },
  { code: "BH", displayName: "Bahrain" },
  { code: "BI", displayName: "Burundi" },
  { code: "BJ", displayName: "Benin" },
  { code: "BL", displayName: "St. Barthélemy" },
  { code: "BM", displayName: "Bermuda" },
  { code: "BN", displayName: "Brunei" },
  { code: "BO", displayName: "Bolivia" },
  { code: "BQ", displayName: "Caribbean Netherlands" },
  { code: "BR", displayName: "Brazil" },
  { code: "BS", displayName: "Bahamas" },
  { code: "BT", displayName: "Bhutan" },
  { code: "BV", displayName: "Bouvet Island" },
  { code: "BW", displayName: "Botswana" },
  { code: "BY", displayName: "Belarus" },
  { code: "BZ", displayName: "Belize" },
  { code: "CA", displayName: "Canada" },
  { code: "CC", displayName: "Cocos (Keeling) Islands" },
  { code: "CD", displayName: "Congo - Kinshasa" },
  { code: "CF", displayName: "Central African Republic" },
  { code: "CG", displayName: "Congo - Brazzaville" },
  { code: "CH", displayName: "Switzerland" },
  { code: "CI", displayName: "Côte d’Ivoire" },
  { code: "CK", displayName: "Cook Islands" },
  { code: "CL", displayName: "Chile" },
  { code: "CM", displayName: "Cameroon" },
  { code: "CN", displayName: "China" },
  { code: "CO", displayName: "Colombia" },
  { code: "CQ", displayName: "Sark" },
  { code: "CR", displayName: "Costa Rica" },
  { code: "CU", displayName: "Cuba" },
  { code: "CV", displayName: "Cape Verde" },
  { code: "CW", displayName: "Curaçao" },
  { code: "CX", displayName: "Christmas Island" },
  { code: "CY", displayName: "Cyprus" },
  { code: "CZ", displayName: "Czechia" },
  { code: "DE", displayName: "Germany" },
  { code: "DJ", displayName: "Djibouti" },
  { code: "DK", displayName: "Denmark" },
  { code: "DM", displayName: "Dominica" },
  { code: "DO", displayName: "Dominican Republic" },
  { code: "DY", displayName: "Benin" },
  { code: "DZ", displayName: "Algeria" },
  { code: "EC", displayName: "Ecuador" },
  { code: "EE", displayName: "Estonia" },
  { code: "EG", displayName: "Egypt" },
  { code: "EH", displayName: "Western Sahara" },
  { code: "ER", displayName: "Eritrea" },
  { code: "ES", displayName: "Spain" },
  { code: "ET", displayName: "Ethiopia" },
  { code: "FI", displayName: "Finland" },
  { code: "FJ", displayName: "Fiji" },
  { code: "FK", displayName: "Falkland Islands" },
  { code: "FM", displayName: "Micronesia" },
  { code: "FO", displayName: "Faroe Islands" },
  { code: "FR", displayName: "France" },
  { code: "GA", displayName: "Gabon" },
  { code: "GB", displayName: "United Kingdom" },
  { code: "GD", displayName: "Grenada" },
  { code: "GE", displayName: "Georgia" },
  { code: "GF", displayName: "French Guiana" },
  { code: "GG", displayName: "Guernsey" },
  { code: "GH", displayName: "Ghana" },
  { code: "GI", displayName: "Gibraltar" },
  { code: "GL", displayName: "Greenland" },
  { code: "GM", displayName: "Gambia" },
  { code: "GN", displayName: "Guinea" },
  { code: "GP", displayName: "Guadeloupe" },
  { code: "GQ", displayName: "Equatorial Guinea" },
  { code: "GR", displayName: "Greece" },
  { code: "GS", displayName: "South Georgia & South Sandwich Islands" },
  { code: "GT", displayName: "Guatemala" },
  { code: "GU", displayName: "Guam" },
  { code: "GW", displayName: "Guinea-Bissau" },
  { code: "GY", displayName: "Guyana" },
  { code: "HK", displayName: "Hong Kong SAR China" },
  { code: "HM", displayName: "Heard & McDonald Islands" },
  { code: "HN", displayName: "Honduras" },
  { code: "HR", displayName: "Croatia" },
  { code: "HT", displayName: "Haiti" },
  { code: "HU", displayName: "Hungary" },
  { code: "HV", displayName: "Burkina Faso" },
  { code: "ID", displayName: "Indonesia" },
  { code: "IE", displayName: "Ireland" },
  { code: "IL", displayName: "Israel" },
  { code: "IM", displayName: "Isle of Man" },
  { code: "IN", displayName: "India" },
  { code: "IO", displayName: "British Indian Ocean Territory" },
  { code: "IQ", displayName: "Iraq" },
  { code: "IR", displayName: "Iran" },
  { code: "IS", displayName: "Iceland" },
  { code: "IT", displayName: "Italy" },
  { code: "JE", displayName: "Jersey" },
  { code: "JM", displayName: "Jamaica" },
  { code: "JO", displayName: "Jordan" },
  { code: "JP", displayName: "Japan" },
  { code: "KE", displayName: "Kenya" },
  { code: "KG", displayName: "Kyrgyzstan" },
  { code: "KH", displayName: "Cambodia" },
  { code: "KI", displayName: "Kiribati" },
  { code: "KM", displayName: "Comoros" },
  { code: "KN", displayName: "St. Kitts & Nevis" },
  { code: "KP", displayName: "North Korea" },
  { code: "KR", displayName: "South Korea" },
  { code: "KW", displayName: "Kuwait" },
  { code: "KY", displayName: "Cayman Islands" },
  { code: "KZ", displayName: "Kazakhstan" },
  { code: "LA", displayName: "Laos" },
  { code: "LB", displayName: "Lebanon" },
  { code: "LC", displayName: "St. Lucia" },
  { code: "LI", displayName: "Liechtenstein" },
  { code: "LK", displayName: "Sri Lanka" },
  { code: "LR", displayName: "Liberia" },
  { code: "LS", displayName: "Lesotho" },
  { code: "LT", displayName: "Lithuania" },
  { code: "LU", displayName: "Luxembourg" },
  { code: "LV", displayName: "Latvia" },
  { code: "LY", displayName: "Libya" },
  { code: "MA", displayName: "Morocco" },
  { code: "MC", displayName: "Monaco" },
  { code: "MD", displayName: "Moldova" },
  { code: "ME", displayName: "Montenegro" },
  { code: "MF", displayName: "St. Martin" },
  { code: "MG", displayName: "Madagascar" },
  { code: "MH", displayName: "Marshall Islands" },
  { code: "MK", displayName: "North Macedonia" },
  { code: "ML", displayName: "Mali" },
  { code: "MM", displayName: "Myanmar (Burma)" },
  { code: "MN", displayName: "Mongolia" },
  { code: "MO", displayName: "Macao SAR China" },
  { code: "MP", displayName: "Northern Mariana Islands" },
  { code: "MQ", displayName: "Martinique" },
  { code: "MR", displayName: "Mauritania" },
  { code: "MS", displayName: "Montserrat" },
  { code: "MT", displayName: "Malta" },
  { code: "MU", displayName: "Mauritius" },
  { code: "MV", displayName: "Maldives" },
  { code: "MW", displayName: "Malawi" },
  { code: "MX", displayName: "Mexico" },
  { code: "MY", displayName: "Malaysia" },
  { code: "MZ", displayName: "Mozambique" },
  { code: "NA", displayName: "Namibia" },
  { code: "NC", displayName: "New Caledonia" },
  { code: "NE", displayName: "Niger" },
  { code: "NF", displayName: "Norfolk Island" },
  { code: "NG", displayName: "Nigeria" },
  { code: "NH", displayName: "Vanuatu" },
  { code: "NI", displayName: "Nicaragua" },
  { code: "NL", displayName: "Netherlands" },
  { code: "NO", displayName: "Norway" },
  { code: "NP", displayName: "Nepal" },
  { code: "NR", displayName: "Nauru" },
  { code: "NU", displayName: "Niue" },
  { code: "NZ", displayName: "New Zealand" },
  { code: "OM", displayName: "Oman" },
  { code: "PA", displayName: "Panama" },
  { code: "PE", displayName: "Peru" },
  { code: "PF", displayName: "French Polynesia" },
  { code: "PG", displayName: "Papua New Guinea" },
  { code: "PH", displayName: "Philippines" },
  { code: "PK", displayName: "Pakistan" },
  { code: "PL", displayName: "Poland" },
  { code: "PM", displayName: "St. Pierre & Miquelon" },
  { code: "PN", displayName: "Pitcairn Islands" },
  { code: "PR", displayName: "Puerto Rico" },
  { code: "PS", displayName: "Palestinian Territories" },
  { code: "PT", displayName: "Portugal" },
  { code: "PW", displayName: "Palau" },
  { code: "PY", displayName: "Paraguay" },
  { code: "QA", displayName: "Qatar" },
  { code: "RE", displayName: "Réunion" },
  { code: "RH", displayName: "Zimbabwe" },
  { code: "RO", displayName: "Romania" },
  { code: "RS", displayName: "Serbia" },
  { code: "RU", displayName: "Russia" },
  { code: "RW", displayName: "Rwanda" },
  { code: "SA", displayName: "Saudi Arabia" },
  { code: "SB", displayName: "Solomon Islands" },
  { code: "SC", displayName: "Seychelles" },
  { code: "SD", displayName: "Sudan" },
  { code: "SE", displayName: "Sweden" },
  { code: "SG", displayName: "Singapore" },
  { code: "SH", displayName: "St. Helena" },
  { code: "SI", displayName: "Slovenia" },
  { code: "SJ", displayName: "Svalbard & Jan Mayen" },
  { code: "SK", displayName: "Slovakia" },
  { code: "SL", displayName: "Sierra Leone" },
  { code: "SM", displayName: "San Marino" },
  { code: "SN", displayName: "Senegal" },
  { code: "SO", displayName: "Somalia" },
  { code: "SR", displayName: "Suriname" },
  { code: "SS", displayName: "South Sudan" },
  { code: "ST", displayName: "São Tomé & Príncipe" },
  { code: "SV", displayName: "El Salvador" },
  { code: "SX", displayName: "Sint Maarten" },
  { code: "SY", displayName: "Syria" },
  { code: "SZ", displayName: "Eswatini" },
  { code: "TC", displayName: "Turks & Caicos Islands" },
  { code: "TD", displayName: "Chad" },
  { code: "TF", displayName: "French Southern Territories" },
  { code: "TG", displayName: "Togo" },
  { code: "TH", displayName: "Thailand" },
  { code: "TJ", displayName: "Tajikistan" },
  { code: "TK", displayName: "Tokelau" },
  { code: "TL", displayName: "Timor-Leste" },
  { code: "TM", displayName: "Turkmenistan" },
  { code: "TN", displayName: "Tunisia" },
  { code: "TO", displayName: "Tonga" },
  { code: "TR", displayName: "Türkiye" },
  { code: "TT", displayName: "Trinidad & Tobago" },
  { code: "TV", displayName: "Tuvalu" },
  { code: "TW", displayName: "Taiwan" },
  { code: "TZ", displayName: "Tanzania" },
  { code: "UA", displayName: "Ukraine" },
  { code: "UG", displayName: "Uganda" },
  { code: "UM", displayName: "U.S. Outlying Islands" },
  { code: "UN", displayName: "United Nations" },
  { code: "US", displayName: "United States" },
  { code: "UY", displayName: "Uruguay" },
  { code: "UZ", displayName: "Uzbekistan" },
  { code: "VA", displayName: "Vatican City" },
  { code: "VC", displayName: "St. Vincent & Grenadines" },
  { code: "VD", displayName: "Vietnam" },
  { code: "VE", displayName: "Venezuela" },
  { code: "VG", displayName: "British Virgin Islands" },
  { code: "VI", displayName: "U.S. Virgin Islands" },
  { code: "VN", displayName: "Vietnam" },
  { code: "VU", displayName: "Vanuatu" },
  { code: "WF", displayName: "Wallis & Futuna" },
  { code: "WS", displayName: "Samoa" },
  { code: "XK", displayName: "Kosovo" },
  { code: "YD", displayName: "Yemen" },
  { code: "YE", displayName: "Yemen" },
  { code: "YT", displayName: "Mayotte" },
  { code: "ZA", displayName: "South Africa" },
  { code: "ZM", displayName: "Zambia" },
  { code: "ZW", displayName: "Zimbabwe" },
] as const satisfies readonly Country[];

export const COUNTRY_CODES = COUNTRIES.map((c) => c.code);

const COUNTRY_CODE_SET = new Set<string>(COUNTRY_CODES);

export function isCountryCode(value: string): boolean {
  return COUNTRY_CODE_SET.has(value);
}
